;;; -*- lexical-binding: t -*-
;;; This file is automatically generated. Do not edit manually.
;;; See `docs/README.org' for the original source.

(when (fboundp 'startup-redirect-eln-cache)
  (startup-redirect-eln-cache
   (expand-file-name "var/eln-cache/" user-emacs-directory)))

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-startup-message t
      ring-bell-function 'ignore
      use-dialog-box nil
      ad-redefinition-action 'accept)

(setq-default frame-title-format '("%b"))

(fset 'yes-or-no-p 'y-or-n-p)

(set-face-attribute 'default nil :font "FiraCode Nerd Font" :height 100)
(set-face-attribute 'fixed-pitch nil :font "FiraCode Nerd Font" :height 100)
(set-face-attribute 'variable-pitch nil :font "NotoSansDisplay Nerd Font" :height 100)

(add-to-list 'default-frame-alist '(foreground-color . "#d6d6d4"))
(add-to-list 'default-frame-alist '(background-color . "#1c1e1f"))

(set-face-foreground 'mode-line "#d6d6d4")
(set-face-background 'mode-line "#2d2e2e")
(set-face-attribute 'mode-line nil :box nil)
(set-face-attribute 'mode-line-inactive nil :box nil)
(setq mode-line-format nil)

(setq initial-major-mode 'fundamental-mode)
(setq initial-scratch-message nil)

(add-to-list 'default-frame-alist '(fullscreen . maximized))

(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6
      native-comp-deferred-compilation t
      warning-minimum-level :error
      package-enable-at-startup nil
      package-quickstart nil
      load-prefer-newer noninteractive)

(set-language-environment "UTF-8")
(setq default-input-method nil)
