;;; -*- lexical-binding: t -*-
;;; This file is automatically generated. Do not edit directly.
;;; See `docs/README.org' for the original source.

(when (fboundp 'startup-redirect-eln-cache)
  (startup-redirect-eln-cache
   (expand-file-name "var/eln-cache/" user-emacs-directory)))

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

(setq package-enable-at-startup nil
      package-quickstart nil
      confirm-kill-processes nil
      inhibit-startup-message t
      inhibit-startup-screen t
      server-client-instructions nil
      use-short-answers t
      set-fringe-mode 10
      column-number-mode t
      size-indication-mode t
      auto-mode-case-fold nil
      ffap-machine-p-known 'reject
      fast-but-imprecise-scrolling t
      frame-inhibit-implied-resize t
      which-func-update-delay 1.0
      inhibit-compacting-font-caches t
      redisplay-skip-fontification-on-input t
      command-line-x-option-alist nil
      ring-bell-function 'ignore
      use-dialog-box nil
      mode-line-format nil
      default-input-method nil
      initial-major-mode 'fundamental-mode
      initial-scratch-message nil
      gc-cons-threshold (* 100 1024 1024) ; 100 MiB
      gc-cons-percentage 0.6
      read-process-output-max (* 5 1024 1024) ; 5 MiB
      large-file-warning-threshold (* 100 1024 1024) ; 100 MiB
      load-prefer-newer t
      native-comp-jit-compilation t
      ad-redefinition-action 'accept
      warning-minimum-level :error
      warning-minimum-log-level :debug)

(set-language-environment "UTF-8")

(setq-default frame-title-format '("%b"))

(add-to-list 'default-frame-alist '(foreground-color . "#d6d6d4"))
(add-to-list 'default-frame-alist '(background-color . "#1c1e1f"))

(set-face-foreground 'mode-line "#d6d6d4")
(set-face-background 'mode-line "#2d2e2e")
(set-face-attribute 'mode-line nil :box nil)
(set-face-attribute 'mode-line-inactive nil :box nil)
