;;; -*- lexical-binding: t -*-
;;; This file is automatically generated. Do not edit directly.
;;; See `docs/README.org' for the original source.

(when (version< emacs-version "30")
  (error "Emacs version < 30 is not supported"))

(defconst lec/doc-directory (file-name-concat user-emacs-directory "docs")
  "Directory where literate configuration in org-mode lies.")

(defconst lec/etc-directory (file-name-concat user-emacs-directory "etc")
  "Directory where external configurations for packages goes.")

(defconst lec/var-directory (file-name-concat user-emacs-directory "var")
  "Directory where temporary files and packages resources goes.")

(defconst lec/doc-file (file-name-concat lec/doc-directory "README.org")
  "Documentation file for the configuration.")

(defconst lec/tangled-doc-file (file-name-concat lec/var-directory "tangled-conf.el")
  "File destination for tangled code blocks from the documentation.")

(setq straight-check-for-modifications '(check-on-save find-when-checking)
      straight-base-dir lec/var-directory
      straight-repository-branch "develop"
      comp-deferred-compilation-deny-list nil)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" lec/var-directory))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq use-package-always-ensure t
      straight-use-package-by-default t)

(use-package benchmark-init
  :hook (after-init . benchmark-init/deactivate)
  :init (benchmark-init/activate))

(use-package org
  :defer t)

(defun lec/--tangle-documentation ()
  "Tangle the org file given to cache directory after renaming it."
  (interactive)
  (org-babel-tangle-file lec/doc-file lec/tangled-doc-file))

(defun lec/--editing-documentation ()
  "If the the file currently edited is the documentation configuration, tangle
the code blocks."
  (when (string-match lec/doc-file buffer-file-name)
    (lec/--tangle-documentation)))

(defun lec/--add-headers ()
  "Add headers at the start of tangled files with a simple warning about how
they should not be modified directly."
  (goto-char (point-min))
  (insert ";;; -*- lexical-binding: t -*-\n")
  (insert ";;; This file is automatically generated. Do not edit directly.\n")
  (insert ";;; See `docs/README.org' for the original source.\n\n")
  (save-buffer))

(add-hook 'after-save-hook #'lec/--editing-documentation)
(add-hook 'org-babel-post-tangle-hook #'lec/--add-headers)

(unless (file-exists-p lec/tangled-doc-file)
  (lec/--tangle-documentation))

(load lec/tangled-doc-file)

(setq-default custom-file (file-name-concat lec/etc-directory "custom.el"))
(load custom-file 'noerror 'nomessage)
