;;; -*- lexical-binding: t -*-
;;; This file is automatically generated. Do not edit manually.
;;; See `docs/README.org' for the original source.

(when (version< emacs-version "27")
  (message "Emacs version < 27 do not support early-init.el. Load it manually.")
  (load (concat
         (file-name-directory load-file-name)
         "early-init")
        'noerror 'nomessage))

(defconst lec/etc-directory (file-name-concat user-emacs-directory "etc")
  "Directory where external configurations for packages goes.")

(defconst lec/doc-directory (file-name-concat user-emacs-directory "docs")
  "Directory where literate configuration in org-mode lies.")

(defconst lec/var-directory (file-name-concat user-emacs-directory "var")
  "Directory where temporary files and packages resources goes.")

(defconst lec/doc-file (file-name-concat lec/doc-directory "README.org")
  "Documentation file for the configuration.")

(defconst lec/tangled-doc-file (file-name-concat lec/var-directory "tangled-conf.el")
  "File destination for tangled code blocks from the documentation.")

(setq straight-check-for-modifications '(check-on-save find-when-checking))
(setq straight-base-dir lec/var-directory)
(setq straight-repository-branch "develop")
(setq comp-deferred-compilation-deny-list nil)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" lec/var-directory))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq use-package-always-ensure t)
(setq straight-use-package-by-default t)

(use-package org)

(defun lec/tangle-documentation ()
  "Tangle the org file given to cache directory after renaming it."
  (interactive)
  (org-babel-tangle-file lec/doc-file lec/tangled-doc-file))

(defun lec/--tangle-current-documentation ()
  "If the the file currently edited is the documentation configuration, tangle
the code blocks."
  (when (string-match lec/doc-file buffer-file-name)
    (lec/tangle-documentation)))

(defun lec/--add-tangle-headers ()
  "Add headers at the start of tangled files specifying they should not be
modified manually."
  (goto-char (point-min))
  (insert ";;; -*- lexical-binding: t -*-\n")
  (insert ";;; This file is automatically generated. Do not edit manually.\n")
  (insert ";;; See `docs/README.org' for the original source.\n\n")
  (save-buffer))

(unless (file-exists-p lec/tangled-doc-file)
  (lec/tangle-documentation))

(add-hook 'after-save-hook #'lec/--tangle-current-documentation)
(add-hook 'org-babel-post-tangle-hook #'lec/--add-tangle-headers)

(load lec/tangled-doc-file)

(setq-default custom-file (file-name-concat lec/etc-directory "custom.el"))
(load custom-file 'noerror 'nomessage)
