;;; -*- lexical-binding: t -*-
;;; This file is automatically generated. Do not edit manually.
;;; See `docs/README.org' for the original source.

(when (version< emacs-version "27")
  (message "Emacs version < 27 do not support early-init.el. Load it manually.")
  (load (concat
         (file-name-directory load-file-name)
         "early-init")
        'noerror 'nomessage))

(defun concat-path (&rest parts)
  (cl-reduce (lambda (a b) (expand-file-name b a)) parts))

(defconst lec/etc-directory (concat-path user-emacs-directory "etc")
  "Directory where external configurations for packages goes.")

(defconst lec/doc-directory (concat-path user-emacs-directory "docs")
  "Directory where literate configuration in org-mode lies.")

(defconst lec/var-directory (concat-path user-emacs-directory "var")
  "Directory where temporary files and packages resources goes.")

(defconst lec/doc-file (concat-path lec/doc-directory "README.org")
  "Documentation file for the configuration.")

(defconst lec/tangled-doc-file (concat-path lec/var-directory "tangled-conf.el")
  "File destination for tangled code blocks from the documentation.")

(defun lec/tangle-documentation ()
  "Tangle the org file given to cache directory after renaming it."
  (interactive)
  (require 'org)
  (org-babel-tangle-file lec/doc-file lec/tangled-doc-file))

(defun lec/--tangle-current-documentation ()
  "If the the file currently edited is the documentation configuration, tangle
the code blocks."
  (when (string-match lec/doc-file buffer-file-name)
    (lec/tangle-documentation)))

(defun lec/--add-tangle-headers ()
  "Add headers at the start of tangled files specifying they should not be
modified manually."
  (goto-char (point-min))
  (insert ";;; -*- lexical-binding: t -*-\n")
  (insert ";;; This file is automatically generated. Do not edit manually.\n")
  (insert ";;; See `docs/README.org' for the original source.\n\n")
  (save-buffer))

(unless (file-exists-p lec/tangled-doc-file)
  (lec/tangle-documentation))

(add-hook 'after-save-hook #'lec/--tangle-current-documentation)
(add-hook 'org-babel-post-tangle-hook #'lec/--add-tangle-headers)

(load lec/tangled-doc-file)

(setq-default custom-file (concat-path lec/etc-directory "custom.el"))
(load custom-file 'noerror 'nomessage)
